### ISSUE TITLE
cannot read netCDF with more than one unlimited dimension

### ISSUE THREAD

**Issue by mathause** [shoyer/h5netcdf#42]
``` python

import numpy as np
import xarray as xr
import h5netcdf
import h5netcdf.legacyapi as netCDF4

# create a netCDF file with more than one unlimited dimension

x = np.arange(10.0)
ds = xr.Dataset({'data': ('dim0', x)}, 
             {'dim0': ('dim0', x), 'dim1': ('dim1', x)})

ds.to_netcdf('tst.nc', unlimited_dims=['dim0', 'dim1'])

# try to read it with h5netcdf

h5netcdf.File('tst.nc', 'r')
netCDF4.Dataset('tst.nc', 'r')

# works when using netCDF4
xr.Dataset('tst.nc', engine='netcdf4')

```

This yields `ValueError: Each dimension with an actual length must have a 'REFERENCE_LIST' attribute`. I think this should work. 

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.120-45-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.2+dev6.g9261601
pandas: 0.22.0
numpy: 1.14.2
scipy: 1.0.1
netCDF4: 1.3.1
h5netcdf: 0.5.0
h5py: 2.7.1
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: 1.0.0
dask: 0.17.2
distributed: 1.21.3
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.0.1
pip: 9.0.2
conda: None
pytest: 3.4.2
IPython: 6.2.1
sphinx: None

</details>

**Comment by shoyer** [comment]
Agreed, this should work. I'm marking this as a bug -- any interest in trying to figure this out?

**Comment by mathause** [comment]
I just checked and this no longer raises an error in master. So #40 seems to have fixed the issue.

**Comment by mathause** [comment]
I looked a bit deeper and I think the problem was that my `'dim1'` did not belong to anything. So I think this is actually the same issue as #39. Thus this should be covered by 

https://github.com/shoyer/h5netcdf/blob/master/h5netcdf/tests/test_h5netcdf.py#L742-L749

So I think we can actually close this.

**Comment by shoyer** [comment]
OK, thanks for looking into it. I issued the v0.5.1 release, which should be up on pypi now.
