### ISSUE TITLE
Test suite is flaky due to failure to connect to h5pyd test server

### ISSUE THREAD

**Issue by shoyer** [shoyer/h5netcdf#47]
Over the last few months, h5netcdf's test suite [has been failing](https://travis-ci.org/shoyer/h5netcdf/builds) about 50% of the time on Travis-CI:
<img width="1055" alt="screen shot 2018-08-18 at 10 22 12 pm" src="https://user-images.githubusercontent.com/1217238/44305804-de1f7d80-a335-11e8-921b-2281a13f76b6.png">

This is just enough to start to get annoying.

In particular, it fails at:
```
$ curl ${HS_ENDPOINT}/about && export WITHRESTAPI=--restapi
curl: (7) Failed to connect to 52.4.181.237 port 5104: Connection timed out
The command "curl ${HS_ENDPOINT}/about && export WITHRESTAPI=--restapi" failed and exited with 7 during .
Your build has been stopped.
```

@ajelenak-thg any ideas?

**Comment by jreadey** [comment]
Hey @shoyer - could you change the HS_ENDPOINT to http://hsdshdflab.hdfgroup.org? 
I'll send you credentials via email.

**Comment by shoyer** [comment]
@jreadey sure thing -- you can reach me at shoyer@gmail.com

**Comment by shoyer** [comment]
@jreadey thanks for your help -- this seems to be working again now.

**Comment by shoyer** [comment]
These are failing on Travis-CI again with "OSError: [Errno 404] Not Found", e.g., see https://travis-ci.org/shoyer/h5netcdf/jobs/539292517

I've disabled them for now in https://github.com/shoyer/h5netcdf/pull/58 but would be happy to bring them back later if we can get them working consistently.

**Comment by jreadey** [comment]
I think this is due to the target folder not being present on the server.  I've re-created them, can you try enabling the travis test to see if that resolves the issue?

**Comment by shoyer** [comment]
Thanks @jreadey, we're back in business!

see https://github.com/shoyer/h5netcdf/pull/59
