### ISSUE TITLE
h5py 2.10.0 deprecation warning

### ISSUE THREAD

**Issue by dcherian** [shoyer/h5netcdf#62]
> H5pyDeprecationWarning('other_ds.dims.create_scale(ds, name) is deprecated. Use ds.make_scale(name) instead.',)

This new warning is the root cause of https://github.com/pydata/xarray/issues/3300

**Comment by kmuehlbauer** [comment]
@dcherian see #69

**Comment by dcherian** [comment]
Thanks @kmuehlbauer !
