### ISSUE TITLE
h5py.File needs access mode specified

### ISSUE THREAD

**Issue by RizzerOnGitHub** [shoyer/h5netcdf#74]
Looks like commit d1e4c0f missed a couple.

[h5py_File_mode.patch.txt](https://github.com/shoyer/h5netcdf/files/4431222/h5py_File_mode.patch.txt)

**Comment by RizzerOnGitHub** [comment]
Incidentally,  release v0.8.0 appears on pypi, but not here. Does it need to be pushed here?

**Comment by dcherian** [comment]
@RizzerOnGithub It would be easier if you opened a pull request

**Comment by RizzerOnGitHub** [comment]
https://github.com/shoyer/h5netcdf/pull/75

**Comment by shoyer** [comment]
Thanks for the pull request!
