### ISSUE TITLE
Missing git tag for 0.8.0 release

### ISSUE THREAD

**Issue by ashwinvis** [shoyer/h5netcdf#76]
I noticed that 0.8.0 is out on PyPI and conda-forge, but not tagged on GitHub. Also, the the changelog says TBD here and "Version 0.8.0 (February 4, 2020):" on PyPI. Seems like the release commit is missing.

**Comment by shoyer** [comment]
Good catch!

I pushed the missing commit/tag, but it required rewriting history because unfortunately I merged #75 in the meantime :(

**Comment by shoyer** [comment]
I just pushed 0.8.1, too. It should be up on pypi and have a git tag, this time.
